### ISSUE TITLE
AliTrainHelper in AliPhysics?

### ISSUE THREAD

**Issue by raymondEhlers** [ALICEYale/alice-yale-dev#2]
Hi @aiola ,

At random, I noticed your PWG::Tools::AliTrainHelper class - it looks quite useful! I don't seem it in AliPhysics. Is it there and I'm just not seeing it?

**Comment by aiola** [comment]
Hi, indeed for the moment I did not push it to the central repo. I would like to test it a bit more and maybe add some more functions before pushing. You are of course welcome to start using and improving it as you like (in principle it is not needed to have it on the grid, since you only need it to prepare the analysis manager locally).
Best,
Salvatore

**Comment by raymondEhlers** [comment]
Okay, cool! Where is it located?

**Comment by aiola** [comment]
Oh, sorry, forgot to add the link: https://github.com/aiola/AliPhysics/tree/feature-utils

**Comment by raymondEhlers** [comment]
Perfect, thanks!
